2025-05-13 16:24:19 - app - INFO - Logger configured successfully
2025-05-13 16:24:20 - app - INFO - Logger configured successfully
2025-05-13 16:25:17 - app - INFO - Logger configured successfully
2025-05-13 16:25:27 - app - INFO - Logger configured successfully
2025-05-13 16:25:28 - app - INFO - Logger configured successfully
2025-05-13 16:29:01 - app - INFO - Logger configured successfully
2025-05-13 16:29:01 - app - INFO - redis and db startup...
2025-05-13 16:29:40 - app - INFO - Logger configured successfully
2025-05-13 16:29:40 - app - INFO - redis and db startup...
2025-05-13 16:44:18 - app - INFO - Logger configured successfully
2025-05-13 16:44:19 - app - INFO - Logger configured successfully
2025-05-13 16:44:19 - app - INFO - redis and db startup...
2025-05-13 16:44:35 - app - INFO - redis and db shutdown...
2025-05-13 16:46:19 - app - INFO - Logger configured successfully
2025-05-13 16:46:20 - app - INFO - Logger configured successfully
2025-05-13 16:46:20 - app - INFO - redis and db startup...
2025-05-13 16:46:24 - app - INFO - redis and db shutdown...
2025-05-13 16:49:00 - app - INFO - Logger configured successfully
2025-05-13 16:49:01 - app - INFO - Logger configured successfully
2025-05-13 16:49:02 - app - INFO - redis and db startup...
2025-05-13 16:49:04 - app - INFO - redis and db shutdown...
2025-05-13 16:49:17 - app - INFO - Logger configured successfully
2025-05-13 16:49:18 - app - INFO - Logger configured successfully
2025-05-13 16:49:19 - app - INFO - redis and db startup...
2025-05-13 16:53:30 - app - INFO - redis and db shutdown...
2025-05-13 16:53:37 - app - INFO - Logger configured successfully
2025-05-13 16:53:39 - app - INFO - Logger configured successfully
2025-05-13 16:53:39 - app - INFO - redis and db startup...
2025-05-13 17:13:50 - app - INFO - Logger configured successfully
2025-05-13 17:13:51 - app - INFO - Logger configured successfully
2025-05-13 17:13:51 - app - INFO - redis and db startup...
2025-05-13 17:14:10 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:18:29 - app - INFO - redis and db shutdown...
2025-05-13 17:18:29 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-13 17:18:31 - app - INFO - Logger configured successfully
2025-05-13 17:18:31 - app - INFO - redis and db startup...
2025-05-13 17:18:44 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:20:44 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:20:44 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:20:49 - app.routers.sights - INFO - get_sight_detail executed in 0.01 seconds
2025-05-13 17:21:26 - app.routers.sights - INFO - get_sight_detail executed in 0.00 seconds
2025-05-13 17:21:27 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:21:27 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:21:55 - app.routers.sights - INFO - get_sight_detail executed in 0.01 seconds
2025-05-13 17:38:04 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:04 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:08 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:08 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:33 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:33 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:35 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:35 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-14 10:55:41 - app - INFO - Logger configured successfully
2025-05-14 10:55:42 - app - INFO - Logger configured successfully
2025-05-14 10:55:42 - app - INFO - redis and db startup...
2025-05-14 10:56:04 - app - INFO - redis and db shutdown...
2025-05-14 10:56:55 - app - INFO - Logger configured successfully
2025-05-14 10:56:57 - app - INFO - Logger configured successfully
2025-05-14 10:56:57 - app - INFO - redis and db startup...
2025-05-14 10:57:22 - app.sight.router - ERROR - get_sight_detail failed after 4.08 seconds: Error connecting to localhost:6379. Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379).
2025-05-14 10:57:22 - app.sight.router - ERROR - Traceback (most recent call last):
  File "C:\Users\12269\Desktop\fast_api_service\venv\lib\site-packages\aioredis\connection.py", line 692, in connect
    await self._connect()
  File "C:\Users\12269\Desktop\fast_api_service\venv\lib\site-packages\aioredis\connection.py", line 719, in _connect
    reader, writer = await asyncio.open_connection(
  File "D:\dev\python\python3.8\lib\asyncio\streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "D:\dev\python\python3.8\lib\asyncio\base_events.py", line 1025, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\12269\Desktop\fast_api_service\app\utils\logger.py", line 75, in async_wrapper
    result = await func(*args, **kwargs)
  File "c:\Users\12269\Desktop\fast_api_service\app\sight\router.py", line 51, in get_sight_detail
    cached_response = await get_Info_from_redis(redis, cache_key)
  File "c:\Users\12269\Desktop\fast_api_service\app\sight\router.py", line 32, in get_Info_from_redis
    cached = await redis.get(cache_key)
  File "C:\Users\12269\Desktop\fast_api_service\venv\lib\site-packages\aioredis\client.py", line 1082, in execute_command
    conn = self.connection or await pool.get_connection(command_name, **options)
  File "C:\Users\12269\Desktop\fast_api_service\venv\lib\site-packages\aioredis\connection.py", line 1416, in get_connection
    await connection.connect()
  File "C:\Users\12269\Desktop\fast_api_service\venv\lib\site-packages\aioredis\connection.py", line 698, in connect
    raise ConnectionError(self._error_message(e))
aioredis.exceptions.ConnectionError: Error connecting to localhost:6379. Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379).

2025-05-14 10:57:29 - app - INFO - redis and db shutdown...
