2025-05-13 17:14:10 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:18:29 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-13 17:18:44 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:20:44 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:20:44 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:21:27 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:21:27 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:04 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:04 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:08 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:08 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:33 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:33 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:35 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-13 17:38:35 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-14 10:57:22 - app.sight.router - ERROR - get_sight_detail failed after 4.08 seconds: Error connecting to localhost:6379. Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379).
2025-05-14 10:57:22 - app.sight.router - ERROR - Traceback (most recent call last):
  File "C:\Users\12269\Desktop\fast_api_service\venv\lib\site-packages\aioredis\connection.py", line 692, in connect
    await self._connect()
  File "C:\Users\12269\Desktop\fast_api_service\venv\lib\site-packages\aioredis\connection.py", line 719, in _connect
    reader, writer = await asyncio.open_connection(
  File "D:\dev\python\python3.8\lib\asyncio\streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "D:\dev\python\python3.8\lib\asyncio\base_events.py", line 1025, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\12269\Desktop\fast_api_service\app\utils\logger.py", line 75, in async_wrapper
    result = await func(*args, **kwargs)
  File "c:\Users\12269\Desktop\fast_api_service\app\sight\router.py", line 51, in get_sight_detail
    cached_response = await get_Info_from_redis(redis, cache_key)
  File "c:\Users\12269\Desktop\fast_api_service\app\sight\router.py", line 32, in get_Info_from_redis
    cached = await redis.get(cache_key)
  File "C:\Users\12269\Desktop\fast_api_service\venv\lib\site-packages\aioredis\client.py", line 1082, in execute_command
    conn = self.connection or await pool.get_connection(command_name, **options)
  File "C:\Users\12269\Desktop\fast_api_service\venv\lib\site-packages\aioredis\connection.py", line 1416, in get_connection
    await connection.connect()
  File "C:\Users\12269\Desktop\fast_api_service\venv\lib\site-packages\aioredis\connection.py", line 698, in connect
    raise ConnectionError(self._error_message(e))
aioredis.exceptions.ConnectionError: Error connecting to localhost:6379. Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379).

2025-05-14 16:52:36 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-19 10:56:04 - app.routers.sights - ERROR - Error creating sight: 2 validation errors for SightResponse
profile
  Error extracting attribute: StatementError: (sqlalchemy.exc.MissingGreenlet) greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place?
[SQL: SELECT sight_profile.id AS sight_profile_id, sight_profile.img AS sight_profile_img, sight_profile.address AS sight_profile_address, sight_profile.`explain` AS sight_profile_explain, sight_profile.open_time AS sight_profile_open_time, sight_profile.tel AS sight_profile_tel, sight_profile.level AS sight_profile_level, sight_profile.tags AS sight_profile_tags, sight_profile.attention AS sight_profile_attention, sight_profile.location AS sight_profile_location, sight_profile.sight_id AS sight_profile_sight_id 
FROM sight_profile 
WHERE %s = sight_profile.sight_id]
[parameters: [{'%(1890917563504 param)s': 0}]]
(Background on this error at: https://sqlalche.me/e/20/xd2s) [type=get_attribute_error, input_value=<app.sight.models.Sight o...t at 0x000001B8437B7370>, input_type=Sight]
    For further information visit https://errors.pydantic.dev/2.10/v/get_attribute_error
tickets
  Error extracting attribute: StatementError: (sqlalchemy.exc.MissingGreenlet) greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place?
[SQL: SELECT sight_ticket.id AS sight_ticket_id, sight_ticket.sight_id AS sight_ticket_sight_id, sight_ticket.name AS sight_ticket_name, sight_ticket.`desc` AS sight_ticket_desc, sight_ticket.type AS sight_ticket_type, sight_ticket.price AS sight_ticket_price, sight_ticket.discount AS sight_ticket_discount, sight_ticket.total AS sight_ticket_total, sight_ticket.remain AS sight_ticket_remain, sight_ticket.expire_date AS sight_ticket_expire_date, sight_ticket.return_policy AS sight_ticket_return_policy, sight_ticket.is_valid AS sight_ticket_is_valid, sight_ticket.created_at AS sight_ticket_created_at, sight_ticket.updated_at AS sight_ticket_updated_at 
FROM sight_ticket 
WHERE %s = sight_ticket.sight_id]
[parameters: [{'%(1890918115408 param)s': 0}]]
(Background on this error at: https://sqlalche.me/e/20/xd2s) [type=get_attribute_error, input_value=<app.sight.models.Sight o...t at 0x000001B8437B7370>, input_type=Sight]
    For further information visit https://errors.pydantic.dev/2.10/v/get_attribute_error
2025-05-19 10:56:29 - app.routers.sights - ERROR - Error creating sight: 2 validation errors for SightResponse
profile
  Error extracting attribute: StatementError: (sqlalchemy.exc.MissingGreenlet) greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place?
[SQL: SELECT sight_profile.id AS sight_profile_id, sight_profile.img AS sight_profile_img, sight_profile.address AS sight_profile_address, sight_profile.`explain` AS sight_profile_explain, sight_profile.open_time AS sight_profile_open_time, sight_profile.tel AS sight_profile_tel, sight_profile.level AS sight_profile_level, sight_profile.tags AS sight_profile_tags, sight_profile.attention AS sight_profile_attention, sight_profile.location AS sight_profile_location, sight_profile.sight_id AS sight_profile_sight_id 
FROM sight_profile 
WHERE %s = sight_profile.sight_id]
[parameters: [{'%(1890917563504 param)s': 0}]]
(Background on this error at: https://sqlalche.me/e/20/xd2s) [type=get_attribute_error, input_value=<app.sight.models.Sight o...t at 0x000001B8438004C0>, input_type=Sight]
    For further information visit https://errors.pydantic.dev/2.10/v/get_attribute_error
tickets
  Error extracting attribute: StatementError: (sqlalchemy.exc.MissingGreenlet) greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place?
[SQL: SELECT sight_ticket.id AS sight_ticket_id, sight_ticket.sight_id AS sight_ticket_sight_id, sight_ticket.name AS sight_ticket_name, sight_ticket.`desc` AS sight_ticket_desc, sight_ticket.type AS sight_ticket_type, sight_ticket.price AS sight_ticket_price, sight_ticket.discount AS sight_ticket_discount, sight_ticket.total AS sight_ticket_total, sight_ticket.remain AS sight_ticket_remain, sight_ticket.expire_date AS sight_ticket_expire_date, sight_ticket.return_policy AS sight_ticket_return_policy, sight_ticket.is_valid AS sight_ticket_is_valid, sight_ticket.created_at AS sight_ticket_created_at, sight_ticket.updated_at AS sight_ticket_updated_at 
FROM sight_ticket 
WHERE %s = sight_ticket.sight_id]
[parameters: [{'%(1890918115408 param)s': 0}]]
(Background on this error at: https://sqlalche.me/e/20/xd2s) [type=get_attribute_error, input_value=<app.sight.models.Sight o...t at 0x000001B8438004C0>, input_type=Sight]
    For further information visit https://errors.pydantic.dev/2.10/v/get_attribute_error
2025-05-19 10:57:14 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-19 10:57:27 - app.routers.sights - ERROR - Error creating sight: 2 validation errors for SightResponse
profile
  Error extracting attribute: StatementError: (sqlalchemy.exc.MissingGreenlet) greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place?
[SQL: SELECT sight_profile.id AS sight_profile_id, sight_profile.img AS sight_profile_img, sight_profile.address AS sight_profile_address, sight_profile.`explain` AS sight_profile_explain, sight_profile.open_time AS sight_profile_open_time, sight_profile.tel AS sight_profile_tel, sight_profile.level AS sight_profile_level, sight_profile.tags AS sight_profile_tags, sight_profile.attention AS sight_profile_attention, sight_profile.location AS sight_profile_location, sight_profile.sight_id AS sight_profile_sight_id 
FROM sight_profile 
WHERE %s = sight_profile.sight_id]
[parameters: [{'%(2025532174496 param)s': 0}]]
(Background on this error at: https://sqlalche.me/e/20/xd2s) [type=get_attribute_error, input_value=<app.sight.models.Sight o...t at 0x000001D79B203EB0>, input_type=Sight]
    For further information visit https://errors.pydantic.dev/2.10/v/get_attribute_error
tickets
  Error extracting attribute: StatementError: (sqlalchemy.exc.MissingGreenlet) greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place?
[SQL: SELECT sight_ticket.id AS sight_ticket_id, sight_ticket.sight_id AS sight_ticket_sight_id, sight_ticket.name AS sight_ticket_name, sight_ticket.`desc` AS sight_ticket_desc, sight_ticket.type AS sight_ticket_type, sight_ticket.price AS sight_ticket_price, sight_ticket.discount AS sight_ticket_discount, sight_ticket.total AS sight_ticket_total, sight_ticket.remain AS sight_ticket_remain, sight_ticket.expire_date AS sight_ticket_expire_date, sight_ticket.return_policy AS sight_ticket_return_policy, sight_ticket.is_valid AS sight_ticket_is_valid, sight_ticket.created_at AS sight_ticket_created_at, sight_ticket.updated_at AS sight_ticket_updated_at 
FROM sight_ticket 
WHERE %s = sight_ticket.sight_id]
[parameters: [{'%(2025532155024 param)s': 0}]]
(Background on this error at: https://sqlalche.me/e/20/xd2s) [type=get_attribute_error, input_value=<app.sight.models.Sight o...t at 0x000001D79B203EB0>, input_type=Sight]
    For further information visit https://errors.pydantic.dev/2.10/v/get_attribute_error
2025-05-19 11:00:59 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-19 11:01:51 - app.routers.sights - ERROR - Error creating sight: Multiple rows were found when one or none was required
2025-05-19 11:09:10 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-19 17:20:35 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-20 09:46:09 - app.routers.sights - ERROR - Error deleting sight 0: Error connecting to localhost:6379. Multiple exceptions: [Errno 10061] Connect call failed ('::1', 6379, 0, 0), [Errno 10061] Connect call failed ('127.0.0.1', 6379).
2025-05-20 09:47:19 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-20 10:23:51 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-20 10:39:15 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-20 14:57:22 - app.routers.sights - ERROR - Error deleting sight 0: (pymysql.err.IntegrityError) (1048, "Column 'sight_id' cannot be null")
[SQL: UPDATE sight_profile SET sight_id=%s WHERE sight_profile.id = %s]
[parameters: (None, 0)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-05-20 15:01:58 - app.routers.sights - ERROR - Error deleting sight 0: (pymysql.err.IntegrityError) (1048, "Column 'sight_id' cannot be null")
[SQL: UPDATE sight_profile SET sight_id=%s WHERE sight_profile.id = %s]
[parameters: (None, 0)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-05-20 15:01:58 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-20 15:06:58 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-20 15:09:24 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-20 15:09:24 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-20 15:09:31 - app.routers.sights - ERROR - Error caching data: Invalid input of type: 'dict'. Convert to a bytes, string, int or float first.
2025-05-20 15:09:37 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-20 15:09:37 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-20 15:09:42 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-20 15:09:42 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-20 15:09:45 - app.routers.sights - ERROR - Error caching data: Invalid input of type: 'dict'. Convert to a bytes, string, int or float first.
2025-05-20 15:09:47 - app.routers.sights - ERROR - Error caching data: Invalid input of type: 'dict'. Convert to a bytes, string, int or float first.
2025-05-20 15:09:56 - app.routers.sights - ERROR - Error caching data: Invalid input of type: 'dict'. Convert to a bytes, string, int or float first.
2025-05-20 15:09:56 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-20 15:09:56 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-20 15:09:58 - app.routers.sights - ERROR - Error caching data: Invalid input of type: 'dict'. Convert to a bytes, string, int or float first.
2025-05-20 15:10:01 - app.routers.sights - ERROR - Error caching data: Invalid input of type: 'dict'. Convert to a bytes, string, int or float first.
2025-05-20 15:15:22 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-20 15:15:22 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-20 15:15:46 - app.routers.sights - ERROR - Error caching hot sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-20 15:15:46 - app.routers.sights - ERROR - Error caching fine sights data: Invalid input of type: 'list'. Convert to a bytes, string, int or float first.
2025-05-20 15:16:47 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-20 15:17:38 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-20 15:17:38 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-20 15:46:40 - app.routers.sights - ERROR - Error caching data: Invalid input of type: 'dict'. Convert to a bytes, string, int or float first.
2025-05-20 16:08:03 - app.routers.sights - ERROR - Error caching fine sights data: Object of type datetime is not JSON serializable
2025-05-20 16:08:03 - app.routers.sights - ERROR - Error caching hot sights data: Object of type datetime is not JSON serializable
2025-05-20 16:08:09 - app.routers.sights - ERROR - Error caching sight detail 1: Object of type datetime is not JSON serializable
2025-05-20 16:08:17 - app.routers.sights - ERROR - Error caching fine sights data: Object of type datetime is not JSON serializable
2025-05-20 16:08:17 - app.routers.sights - ERROR - Error caching hot sights data: Object of type datetime is not JSON serializable
2025-05-20 16:08:20 - app.routers.sights - ERROR - Error caching hot sights data: Object of type datetime is not JSON serializable
2025-05-20 16:08:20 - app.routers.sights - ERROR - Error caching fine sights data: Object of type datetime is not JSON serializable
2025-05-20 16:09:10 - app.routers.sights - ERROR - Error caching data: Object of type datetime is not JSON serializable
2025-05-20 16:09:15 - app.routers.sights - ERROR - Error caching data: Object of type datetime is not JSON serializable
2025-05-20 16:09:52 - app.routers.sights - ERROR - Error caching hot sights data: Object of type datetime is not JSON serializable
2025-05-20 16:09:52 - app.routers.sights - ERROR - Error caching fine sights data: Object of type datetime is not JSON serializable
2025-05-20 16:10:16 - app.routers.sights - ERROR - Error caching hot sights data: Object of type datetime is not JSON serializable
2025-05-20 16:10:26 - app.routers.sights - ERROR - Error caching hot sights data: Object of type datetime is not JSON serializable
2025-05-20 16:10:26 - app.routers.sights - ERROR - Error caching fine sights data: Object of type datetime is not JSON serializable
2025-05-20 16:10:28 - app.routers.sights - ERROR - Error caching data: Object of type datetime is not JSON serializable
2025-05-20 16:10:29 - app.routers.sights - ERROR - Error caching hot sights data: Object of type datetime is not JSON serializable
2025-05-20 16:10:29 - app.routers.sights - ERROR - Error caching fine sights data: Object of type datetime is not JSON serializable
2025-05-20 16:10:31 - app.routers.sights - ERROR - Error caching data: Object of type datetime is not JSON serializable
2025-05-20 16:10:31 - app.routers.sights - ERROR - Error caching hot sights data: Object of type datetime is not JSON serializable
2025-05-20 16:10:58 - app.routers.sights - ERROR - Error caching fine sights data: Object of type datetime is not JSON serializable
2025-05-20 16:11:06 - app.routers.sights - ERROR - Error caching data: Object of type datetime is not JSON serializable
2025-05-20 16:11:07 - app.routers.sights - ERROR - Error caching hot sights data: Object of type datetime is not JSON serializable
2025-05-20 16:11:07 - app.routers.sights - ERROR - Error caching fine sights data: Object of type datetime is not JSON serializable
2025-05-20 16:11:09 - app.routers.sights - ERROR - Error caching hot sights data: Object of type datetime is not JSON serializable
2025-05-20 16:11:09 - app.routers.sights - ERROR - Error caching fine sights data: Object of type datetime is not JSON serializable
2025-05-20 16:11:13 - app.routers.sights - ERROR - Error caching data: Object of type datetime is not JSON serializable
2025-05-20 16:12:21 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-20 16:12:21 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-20 16:12:53 - app.routers.sights - ERROR - Error caching fine sights data: Object of type datetime is not JSON serializable
2025-05-20 16:12:53 - app.routers.sights - ERROR - Error caching hot sights data: Object of type datetime is not JSON serializable
2025-05-22 17:27:11 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
2025-05-22 17:27:11 - asyncio - ERROR - An open stream object is being garbage collected; call "stream.close()" explicitly.
